# Generated by Django 3.2.3 on 2021-05-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=100)),
                ('request_specialty', models.CharField(choices=[(1, 'Neurology - Dr. Kenneth Chin Wei Yow'), (2, 'Cardiology - Dr. Aw Zhi Wei'), (3, 'Psychiatry - Dr. Leong Chee Kei'), (4, 'Radiology - Dr. Kelwin Chew'), (5, 'Arthroplasty - Dr. Tan Zhi Jun')], max_length=1)),
                ('medical_concern', models.TextField()),
            ],
        ),
    ]
