# Generated by Django 3.2.3 on 2021-05-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_appointment_request_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='request_specialty',
            field=models.CharField(choices=[('1', 'Neurology - Dr. Kenneth Chin Wei Yow'), ('2', 'Cardiology - Dr. Aw Zhi Wei'), ('3', 'Psychiatry - Dr. Leong Chee Kei'), ('4', 'Radiology - Dr. Kelwin Chew'), ('5', 'Arthroplasty - Dr. Tan Zhi Jun')], default='1', max_length=1),
        ),
    ]
