# Generated by Django 3.2.3 on 2021-05-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210522_0545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='M', max_length=1)),
                ('date_of_birth', models.DateField()),
                ('email', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=100)),
                ('health_related_info', models.TextField()),
                ('diagnosis', models.TextField()),
                ('medical_record', models.TextField()),
                ('doctor', models.CharField(choices=[('1', 'Neurology - Dr. Kenneth Chin Wei Yow'), ('2', 'Cardiology - Dr. Aw Zhi Wei'), ('3', 'Psychiatry - Dr. Leong Chee Kei'), ('4', 'Radiology - Dr. Kelwin Chew'), ('5', 'Arthroplasty - Dr. Tan Zhi Jun')], default='1', max_length=1)),
                ('status', models.CharField(default='Registered', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='Pending', max_length=30),
        ),
    ]
